import:
  - ~/.config/alacritty/dracula.yml
font:
  normal:
    family: Caskaydia Cove Nerd Font Mono
    style: SemiLight

  bold:
    family: Caskaydia Cove Nerd Font Mono
    style: Bold

  italic:
    family: Caskaydia Cove
    style: Regular Italic

  bold_italic:
    family: Caskaydia Cove
    style: SemiBold Italic

  size: 12

window:
  padding:
    x: 4
    y: 3

cursor:
  style:
    shape: Beam
  vi_mode_style:
    shape: Beam

env:
  TERM: xterm-256color

key_bindings:
  - { key: V,        mods: Command, action: Paste }
  - { key: C,        mods: Command, action: Copy }
