- defaults:
    link:
      relink: true
      create: true
      force: true
      glob: true

- clean: [ '~' ]

- link:
    ~/.zshrc: config/.zshrc
    ~/.bashrc: config/.bashrc
    ~/.zlogin: config/.zlogin
    ~/key-bindings.zsh: config/key-bindings.zsh
    ~/.zimrc: config/.zimrc
    ~/.gitconfig: config/git/.gitconfig
    ~/.config/BetterDiscord: config/BetterDiscord/**
    ~/.config/btop: config/btop/**
    ~/.config/dunst/dunstrc: config/dunst/dunstrc
    ~/.config/hypr: config/hypr/**
    ~/.config/kitty: config/kitty/**
    ~/.config/picom: config/picom/**
    ~/.config/qtile: config/qtile/**
    ~/.config/rofi: config/rofi/**
    ~/.config/swaylock/config: config/swaylock/config
    ~/.config/wallpaper: config/wallpaper/**
    ~/.config/waybar: config/waybar/**
    ~/.config/alacritty: config/alacritty/**
    ~/.config/micro: config/micro/**
    ~/.mozilla/firefox/gg1e8vcw.default-release/chrome/userChrome.css : config/firefox/chrome/userChrome.css
    ~/.config/posh/config.json: config/posh/config.json
    ~/.config/starship/config.toml: config/starship/config.toml


- shell:
    - [ git submodule update --init --recursive, Installing submodules ]