- defaults:
    link:
      relink: true
      create: true
      force: true
      glob: true

- clean: ["~"]

- link:
    ~/.zshrc: config/.zshrc_arch
    ~/.bashrc: config/.bashrc
    ~/.zlogin: config/.zlogin
    ~/key-bindings.zsh: config/key-bindings.zsh
    ~/.zimrc: config/.zimrc
    ~/.gitconfig: config/git/.gitconfig
    ~/.config/BetterDiscord: config/BetterDiscord/**
    ~/.config/btop: config/btop/**
    ~/.config/dunst/dunstrc: config/dunst/dunstrc
    ~/.config/hypr: config/hypr/**
    ~/.config/picom: config/picom/**
    ~/.config/rofi: config/rofi/**
    ~/.config/wallpaper: config/wallpaper/**
    ~/.config/waybar: config/waybar/**
    ~/.config/starship/config.toml: config/starship/config.toml
    ~/.config/ghostty/config: config/ghostty/config
    ~/.config/discord/settings.json: config/discord/settings.json
    ~/.config/bat/bat.conf: config/bat/bat.conf
    ~/.config/zed/keymap.json: config/zed/keymap_linux.json
    ~/.config/zed/settings.json: config/zed/settings_linux.json
    ~/.config/zed/debug.json: config/zed/debug_python_example.json
    ~/.config/gitui: config/gitui/**
    ~/.config/keybindings-helper: config/keybindings-helper/**

    ~/.config/wlogout/: config/wlogout/**
    ~/.config/btop/**: config/btop/**

- shell:
    - [git submodule update --init --recursive, Installing submodules]
