- defaults:
    link:
      relink: true
      create: true
      force: true
      glob: true


- clean: [ '~' ]

- link:
    ~/.zshrc: config/.zshrc
    ~/.bashrc: config/.bashrc
    ~/key-bindings.zsh: config/key-bindings.zsh
    ~/.zimrc: config/.zimrc
    ~/.gitconfig: config/git/.gitconfig
    ~/.config/karabiner/karabiner.json: config/karabiner/karabiner.json
    ~/config/iterm2: config/iterm2
    ~/.config/posh/config.json: config/posh/config.json
    ~/.config/micro: config/micro/**
    ~/.config/starship/config.toml: config/starship/config.toml

- shell:
    - [ git submodule update --init --recursive, Installing submodules ]