- defaults:
    link:
      relink: true
      create: true
      force: true
      glob: true

- clean: ["~"]

- link:
    ~/.zshrc: config/.zshrc_mac
    ~/.bashrc: config/.bashrc
    ~/key-bindings.zsh: config/key-bindings.zsh
    ~/.zimrc: config/.zimrc
    ~/.gitconfig: config/git/.gitconfig
    ~/.config/karabiner/karabiner.json: config/karabiner/karabiner.json
    ~/config/iterm2: config/iterm2
    ~/.config/micro: config/micro/**
    ~/.config/btop: config/btop/**
    ~/.config/starship/config.toml: config/starship/config.toml
    ~/.config/bat/bat.conf: config/bat/bat.conf
    ~/.config/procs/config.toml: config/procs/config.toml
    ~/.config/zed: config/zed/**
    ~/.config/zed/keymap.json: config/zed/keymap_mac.json
    ~/.config/zed/settings.json: config/zed/settings_mac.json
    ~/.config/atuin: config/atuin/**
    ~/.config/ghostty: config/ghostty/**
    ~/.config/yazi: config/yazi/**
    ~/.config/eza: config/eza/**
    ~/.config/aerospace: config/aerospace/**
    ~/.config/fastfetch: config/fastfetch/**
    ~/.gitkraken/config: config/gitkraken/config
    ~/.gitkraken/themes/: config/gitkraken/themes/**
    ~/.config/mise: config/mise/**
    ~/.config/helix: config/helix/**
    "~/Library/Application Support/com.mitchellh.ghostty/config": config/ghostty/config
    ~/.amethyst.yml: config/amethyst/.amethyst.yml
    ~/.config/delta: config/delta/**
    "~/Library/Application Support/lazygit/config.yml": config/lazygit/config.yml
    "~/Library/Application Support/jesseduffield/lazydocker/config.yml": config/lazydocker/config.yml
    ~/.config/docker: config/docker/**
    # ~/Library/Preferences/com.raycast.macos.plist: config/raycast/com.raycast.macos.plist
    ~/Library/Application Support/aichat: config/aichat/**
    ~/.factory/: config/factory/**
    ~/.factory/AGENTS.md: AGENTS.md
    ~/.claude/CLAUDE.md: AGENTS.md
    ~/.claude/commands: config/claude/commands/**
    ~/.claude/settings.json: config/claude/settings.json
    ~/.claude/skills: config/claude/skills/**
    ~/.factory/mcp.json: config/factory/mcp.json

- shell:
    - [git submodule update --init --recursive, Installing submodules]
