- defaults:
    link:
      relink: true
      create: true
      force: true
      glob: true

- clean: ["~"]

- link:
    ~/.zshrc: config/.zshrc_mac
    ~/.bashrc: config/.bashrc
    ~/key-bindings.zsh: config/key-bindings.zsh
    ~/.zimrc: config/.zimrc
    ~/.gitconfig: config/git/.gitconfig
    ~/.config/karabiner/karabiner.json: config/karabiner/karabiner.json
    ~/config/iterm2: config/iterm2
    ~/.config/micro: config/micro/**
    ~/.config/starship/config.toml: config/starship/config.toml
    ~/.config/bat/bat.conf: config/bat/bat.conf
    ~/.config/zed: config/zed/**
    ~/.config/zed/keymap.json: config/zed/keymap_mac.json
    ~/.config/zed/settings.json: config/zed/settings_mac.json
    ~/.config/atuin: config/atuin/**
    ~/.config/ghostty: config/ghostty/**
    ~/.config/yazi: config/yazi/**
    ~/.gitkraken/config: config/gitkraken/config
    ~/.gitkraken/themes/: config/gitkraken/themes/**
    ~/Library/Application\ Support/com.mitchellh.ghostty/config: config/ghostty/config
    ~/.amethyst.yml: config/amethyst/.amethyst.yml

- shell:
    - [git submodule update --init --recursive, Installing submodules]
