#!/usr/bin/env bash

set -e

DOTBOT_DIR="modules/dotbot"
DOTBOT_BIN="bin/dotbot"
OS=$(uname -s)

# Select proper conf
if [[ $OS == "Darwin" ]]; then
  CONFIG=".mac-conf.yml"
elif [[ $OS == "Linux" ]]; then
  CONFIG=".arch-conf.yml"
else
  echo "Unsupported OS: $OS"
  exit 1
fi

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# Set global $DOTFILES env var in .bashrc if not already present
if ! grep -q "export DOTFILES=" ~/.bashrc 2>/dev/null; then
  echo "export DOTFILES=$PWD" >>~/.bashrc
fi
if ! grep -q "shell/main.sh" ~/.bashrc 2>/dev/null; then
  echo "source $PWD/shell/main.sh" >>~/.bashrc
fi
