// Generated by bin/sync-desktop-theme from config/desktop/theme.json.
pragma Singleton

import QtQuick

QtObject {
    readonly property string fontFamily: "JetBrainsMono Nerd Font"
    readonly property string symbolsFont: "Symbols Nerd Font Mono"
    readonly property color rosewater: "#f5e0dc"
    readonly property color flamingo: "#f2cdcd"
    readonly property color pink: "#f5c2e7"
    readonly property color mauve: "#cba6f7"
    readonly property color red: "#f38ba8"
    readonly property color maroon: "#eba0ac"
    readonly property color peach: "#fab387"
    readonly property color yellow: "#f9e2af"
    readonly property color green: "#a6e3a1"
    readonly property color teal: "#94e2d5"
    readonly property color sky: "#89dceb"
    readonly property color sapphire: "#74c7ec"
    readonly property color blue: "#89b4fa"
    readonly property color lavender: "#b4befe"
    readonly property color text: "#cdd6f4"
    readonly property color subtext1: "#bac2de"
    readonly property color subtext0: "#a6adc8"
    readonly property color overlay2: "#9399b2"
    readonly property color overlay1: "#7f849c"
    readonly property color overlay0: "#6c7086"
    readonly property color surface2: "#585b70"
    readonly property color surface1: "#45475a"
    readonly property color surface0: "#313244"
    readonly property color base: "#1e1e2e"
    readonly property color mantle: "#181825"
    readonly property color crust: "#11111b"
    readonly property color panel: "#21222c"
    readonly property color surface: "#414558"
    readonly property color surfaceRaised: "#393a4b"
    readonly property color surfaceInset: "#303140"
    readonly property color activeSurface: "#354f80"
    readonly property color hoverSurface: "#5f5575"
    readonly property color dangerSurface: "#4d3a55"
    readonly property color primaryText: "#f8f8f2"
    readonly property color mutedText: "#a7abbe"
    readonly property color quietText: "#626784"
    readonly property color accent: "#9580ff"
    readonly property color accentText: "#d4ccff"
    readonly property color success: "#8aff80"
    readonly property color warning: "#ff9580"
    readonly property color danger: "#ff80bf"

    function alpha(color, opacity) {
        return Qt.rgba(color.r, color.g, color.b, opacity)
    }
}
