[project]
name = "codexcli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[openai]>=0.3.21",
    "typer>=0.15.2",
]
